const STATE={authenticated:false,passwordSet:false,theme:{},commandHistory:[],historyIndex:-1,autoScroll:true,sseSource:null};

class ParticleSystem{constructor(c){this.canvas=c;this.ctx=c.getContext('2d');this.particles=[];this.resize();this.init();window.addEventListener('resize',()=>this.resize())}resize(){this.canvas.width=window.innerWidth;this.canvas.height=window.innerHeight}init(){const n=Math.floor((this.canvas.width*this.canvas.height)/8000);this.particles=[];for(let i=0;i<n;i++)this.particles.push({x:Math.random()*this.canvas.width,y:Math.random()*this.canvas.height,vx:(Math.random()-0.5)*0.5,vy:(Math.random()-0.5)*0.5,size:Math.random()*1.5+0.5,opacity:Math.random()*0.5+0.1,pulse:Math.random()*Math.PI*2});this.animate()}animate(){if(!document.body.contains(this.canvas))return;this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height);const fc=getCssVar('--font-color')||'#00FF41';const r=parseInt(fc.slice(1,3),16),g=parseInt(fc.slice(3,5),16),b=parseInt(fc.slice(5,7),16);for(const p of this.particles){p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=this.canvas.width;if(p.x>this.canvas.width)p.x=0;if(p.y<0)p.y=this.canvas.height;if(p.y>this.canvas.height)p.y=0;p.pulse+=0.02;const a=p.opacity+Math.sin(p.pulse)*0.15;this.ctx.fillStyle=`rgba(${r},${g},${b},${a})`;this.ctx.beginPath();this.ctx.arc(p.x,p.y,p.size,0,Math.PI*2);this.ctx.fill()}for(let i=0;i<this.particles.length;i++){for(let j=i+1;j<this.particles.length;j++){const dx=this.particles[i].x-this.particles[j].x,dy=this.particles[i].y-this.particles[j].y,dist=Math.sqrt(dx*dx+dy*dy);if(dist<120){const a=(1-dist/120)*0.08;this.ctx.strokeStyle=`rgba(${r},${g},${b},${a})`;this.ctx.lineWidth=0.5;this.ctx.beginPath();this.ctx.moveTo(this.particles[i].x,this.particles[i].y);this.ctx.lineTo(this.particles[j].x,this.particles[j].y);this.ctx.stroke()}}}requestAnimationFrame(()=>this.animate())}}

document.addEventListener('DOMContentLoaded',()=>{new ParticleSystem(document.getElementById('particleCanvas'));checkAuthStatus();document.addEventListener('keydown',handleKeyboard);const o=document.getElementById('consoleOutput');o.addEventListener('scroll',()=>{const b=o.scrollHeight-o.scrollTop-o.clientHeight<50;STATE.autoScroll=b;document.getElementById('scrollHint').classList.toggle('visible',!b)})});

async function checkAuthStatus(){try{const r=await fetch('/api/auth/status');const d=await r.json();STATE.passwordSet=d.passwordSet;if(d.authenticated){STATE.authenticated=true;showMainScreen();initMainScreen()}else showLoginScreen()}catch(e){showLoginScreen()}}
function showLoginScreen(){document.getElementById('loginScreen').classList.add('active');document.getElementById('mainScreen').classList.remove('active');const s=document.getElementById('setupForm'),l=document.getElementById('loginForm'),g=document.getElementById('loadingIndicator');g.style.display='block';s.style.display='none';l.style.display='none';fetch('/api/auth/status').then(r=>r.json()).then(d=>{g.style.display='none';if(d.passwordSet){l.style.display='block';document.getElementById('loginPassword').focus()}else{s.style.display='block';document.getElementById('setupPassword').focus()}}).catch(()=>{g.style.display='none';l.style.display='block'})}
function showMainScreen(){document.getElementById('loginScreen').classList.remove('active');document.getElementById('mainScreen').classList.add('active');document.getElementById('commandInput').focus()}

async function doSetup(){const p=document.getElementById('setupPassword').value,c=document.getElementById('setupConfirm').value,e=document.getElementById('setupError');if(p.length<6){e.textContent='密码至少需要6位';return}if(p!==c){e.textContent='两次输入的密码不一致';return}try{const r=await fetch('/api/auth/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:p})});const d=await r.json();if(d.success){e.textContent='';document.getElementById('loginPassword').value=p;doLogin()}else e.textContent=d.error||'设置失败'}catch(x){e.textContent='网络错误，请重试'}}
async function doLogin(){const p=document.getElementById('loginPassword').value,e=document.getElementById('loginError');if(!p){e.textContent='请输入密码';return}try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:p})});const d=await r.json();if(d.success){STATE.authenticated=true;showMainScreen();initMainScreen()}else{e.textContent=d.error||'密码错误';document.getElementById('loginPassword').value='';document.getElementById('loginPassword').focus()}}catch(x){e.textContent='网络错误，请检查服务器是否运行'}}
async function doLogout(){try{await fetch('/api/auth/logout',{method:'POST'})}catch(e){}STATE.authenticated=false;if(STATE.sseSource){STATE.sseSource.close();STATE.sseSource=null}showLoginScreen()}

function initMainScreen(){loadTheme();loadCommandHistory();connectSSE();document.getElementById('commandInput').focus()}
async function loadTheme(){try{const r=await fetch('/api/config/get');const d=await r.json();STATE.theme=d;applyThemeFromConfig(d);populateSettingsFromConfig(d)}catch(e){}}
function applyThemeFromConfig(c){if(c['theme.bg_color'])setCssVar('--bg-color',c['theme.bg_color']);if(c['theme.font_color'])setCssVar('--font-color',c['theme.font_color']);if(c['theme.border_color'])setCssVar('--border-color',c['theme.border_color']);if(c['theme.accent_color'])setCssVar('--accent-color',c['theme.accent_color']);if(c['theme.font_size'])setCssVar('--font-size',c['theme.font_size']+'px');if(c['theme.background_opacity'])setCssVar('--bg-opacity',c['theme.background_opacity'])}
function populateSettingsFromConfig(c){const e=id=>document.getElementById(id);const bg=c['theme.bg_color']||'#0C0C0C',fc=c['theme.font_color']||'#00FF41',bc=c['theme.border_color']||'#1A1A2E',ac=c['theme.accent_color']||'#E94560',sz=c['theme.font_size']||'14',op=c['theme.background_opacity']||'1.0';e('themeBgColor').value=bg;e('themeBgColorText').value=bg;e('themeFontColor').value=fc;e('themeFontColorText').value=fc;e('themeBorderColor').value=bc;e('themeBorderColorText').value=bc;e('themeAccentColor').value=ac;e('themeAccentColorText').value=ac;e('themeFontSize').value=sz;e('fontSizeValue').textContent=sz+'px';e('themeOpacity').value=op;e('opacityValue').textContent=op;e('settingsTimeout').value=c['session.timeout_minutes']||'30';e('settingsMaxLines').value=c['max_output_lines']||'5000';e('settingsPort').value=c['port']||'8080';e('settingsHttps').value=c['https.enabled']||'false';e('settingsCertFile').value=c['cert.file']||'';e('settingsWebRoot').value=c['web.root']||'';if(typeof htsToggle==='function')htsToggle()}
async function loadCommandHistory(){try{const r=await fetch('/api/command/history');const d=await r.json();STATE.commandHistory=d.history||[]}catch(e){}}

function connectSSE(){if(STATE.sseSource)STATE.sseSource.close();STATE.sseSource=new EventSource('/api/output/stream');STATE.sseSource.addEventListener('output',e=>{try{const d=JSON.parse(e.data);appendText(d.text,d.color||getCssVar('--font-color'))}catch(x){}});STATE.sseSource.addEventListener('clear',()=>{document.getElementById('consoleOutput').innerHTML=''});STATE.sseSource.onerror=()=>{const s=document.getElementById('connectionStatus');s.classList.add('disconnected');s.querySelector('.status-text').textContent='RECONNECTING...';setTimeout(()=>{if(STATE.sseSource&&STATE.sseSource.readyState===EventSource.OPEN){s.classList.remove('disconnected');s.querySelector('.status-text').textContent='CONNECTED'}},3000)};STATE.sseSource.onopen=()=>{const s=document.getElementById('connectionStatus');s.classList.remove('disconnected');s.querySelector('.status-text').textContent='CONNECTED'}}

function appendText(text,color){if(!text)return;const o=document.getElementById('consoleOutput');const s=document.createElement('span');s.className='output-line';s.style.color=color||getCssVar('--font-color');s.textContent=text;o.appendChild(s);const ml=parseInt(STATE.theme['max_output_lines']||5000);while(o.children.length>ml)o.removeChild(o.firstChild);if(o.textContent.length>10000){const ks=o.children;let hf=Math.floor(ks.length/2);while(hf-->0)o.removeChild(o.firstChild)}if(STATE.autoScroll)o.scrollTop=o.scrollHeight}

function sendCommand(){const i=document.getElementById('commandInput'),c=i.value.trim();if(!c)return;STATE.commandHistory.push(c);STATE.historyIndex=STATE.commandHistory.length;appendText('\n> '+c,getCssVar('--accent-color')||'#E94560');fetch('/api/command/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:c})}).then(r=>r.json()).then(d=>{if(!d.success)appendText('[ERROR] '+d.message,'#FF4444')}).catch(e=>{appendText('[ERROR] 请求失败: '+e.message,'#FF4444')});i.value='';i.focus()}
function clearConsole(){document.getElementById('consoleOutput').innerHTML='';fetch('/api/console/clear',{method:'POST'}).catch(()=>{})}

function handleKeyboard(e){if(!STATE.authenticated){if(e.key==='Enter'){if(document.getElementById('setupForm').style.display!=='none')doSetup();else doLogin()}return}const i=document.getElementById('commandInput'),so=document.getElementById('settingsOverlay').classList.contains('active');if(e.key==='Escape'&&so){toggleSettings();return}if(so)return;if(e.ctrlKey&&e.key==='l'){e.preventDefault();clearConsole();return}if(e.key==='Enter'&&document.activeElement===i){e.preventDefault();sendCommand();return}if(e.key==='ArrowUp'&&document.activeElement===i){e.preventDefault();if(STATE.commandHistory.length>0){STATE.historyIndex=Math.max(0,STATE.historyIndex-1);i.value=STATE.commandHistory[STATE.historyIndex]||''}return}if(e.key==='ArrowDown'&&document.activeElement===i){e.preventDefault();if(STATE.historyIndex<STATE.commandHistory.length-1){STATE.historyIndex++;i.value=STATE.commandHistory[STATE.historyIndex]||''}else{STATE.historyIndex=STATE.commandHistory.length;i.value=''}return}}

function toggleSettings(){const o=document.getElementById('settingsOverlay');o.classList.toggle('active');if(o.classList.contains('active')){fetch('/api/config/get').then(r=>r.json()).then(d=>{STATE.theme=d;populateSettingsFromConfig(d)}).catch(()=>{})}}
function applyThemeLive(){const bg=document.getElementById('themeBgColor').value,fc=document.getElementById('themeFontColor').value,bc=document.getElementById('themeBorderColor').value,ac=document.getElementById('themeAccentColor').value,sz=document.getElementById('themeFontSize').value,op=document.getElementById('themeOpacity').value;setCssVar('--bg-color',bg);setCssVar('--font-color',fc);setCssVar('--border-color',bc);setCssVar('--accent-color',ac);setCssVar('--font-size',sz+'px');setCssVar('--bg-opacity',op);document.getElementById('themeBgColorText').value=bg;document.getElementById('themeFontColorText').value=fc;document.getElementById('themeBorderColorText').value=bc;document.getElementById('themeAccentColorText').value=ac;document.getElementById('fontSizeValue').textContent=sz+'px';document.getElementById('opacityValue').textContent=op}
function syncColorFromText(id){const t=document.getElementById(id+'Text'),c=document.getElementById(id),v=t.value.trim();if(/^#[0-9A-Fa-f]{6}$/.test(v)){c.value=v;applyThemeLive()}}
async function saveTheme(){const p={'theme.bg_color':document.getElementById('themeBgColor').value,'theme.font_color':document.getElementById('themeFontColor').value,'theme.border_color':document.getElementById('themeBorderColor').value,'theme.accent_color':document.getElementById('themeAccentColor').value,'theme.font_size':document.getElementById('themeFontSize').value,'theme.background_opacity':document.getElementById('themeOpacity').value};try{const r=await fetch('/api/config/theme',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();showMsg('themeMsg',d.success?'主题已保存 ✓':'保存失败',d.success?'success':'error')}catch(e){showMsg('themeMsg','网络错误','error')}}
function resetTheme(){['themeBgColor','themeBgColorText'].forEach(i=>document.getElementById(i).value='#0C0C0C');['themeFontColor','themeFontColorText'].forEach(i=>document.getElementById(i).value='#00FF41');['themeBorderColor','themeBorderColorText'].forEach(i=>document.getElementById(i).value='#1A1A2E');['themeAccentColor','themeAccentColorText'].forEach(i=>document.getElementById(i).value='#E94560');document.getElementById('themeFontSize').value='14';document.getElementById('themeOpacity').value='1.0';document.getElementById('fontSizeValue').textContent='14px';document.getElementById('opacityValue').textContent='1.0';applyThemeLive();saveTheme()}
async function changePassword(){const o=document.getElementById('settingsOldPassword').value,n=document.getElementById('settingsNewPassword').value;if(!o||!n){showMsg('passwordMsg','请填写所有字段','error');return}if(n.length<6){showMsg('passwordMsg','新密码至少6位','error');return}try{const r=await fetch('/api/auth/changepassword',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({old_password:o,new_password:n})});const d=await r.json();if(d.success){showMsg('passwordMsg','密码已更新 ✓','success');document.getElementById('settingsOldPassword').value='';document.getElementById('settingsNewPassword').value=''}else showMsg('passwordMsg',d.error||'更新失败','error')}catch(e){showMsg('passwordMsg','网络错误','error')}}
async function saveServerConfig(){const t=document.getElementById('settingsTimeout').value,m=document.getElementById('settingsMaxLines').value;try{const r=await fetch('/api/config/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({'session.timeout_minutes':t,'max_output_lines':m})});const d=await r.json();showMsg('serverConfigMsg',d.success?'配置已保存 ✓':'保存失败',d.success?'success':'error')}catch(e){showMsg('serverConfigMsg','网络错误','error')}}
function htsToggle(){const e=document.getElementById('settingsHttps').value==='true';document.getElementById('ksRow').style.display=e?'':'none';document.getElementById('kpRow').style.display=e?'':'none'}
async function saveNetworkConfig(){const p={};const pt=document.getElementById('settingsPort').value;if(pt)p['port']=pt;const he=document.getElementById('settingsHttps').value;p['https.enabled']=he;const cf=document.getElementById('settingsCertFile').value.trim();if(cf)p['cert.file']=cf;const kf=document.getElementById('settingsKeyFile').value.trim();if(kf)p['key.file']=kf;const wr=document.getElementById('settingsWebRoot').value.trim();p['web.root']=wr;try{const r=await fetch('/api/config/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();const ok=d.success;showMsg('networkConfigMsg',ok?(d.restart?'已保存，服务重启中 ✓':'已保存 ✓'):'保存失败',ok?'success':'error')}catch(e){showMsg('networkConfigMsg','网络错误','error')}}
function showMsg(id,msg,type){const e=document.getElementById(id);e.textContent=msg;e.className='settings-msg '+type;setTimeout(()=>{e.textContent='';e.className='settings-msg'},3000)}
function getCssVar(n){return getComputedStyle(document.documentElement).getPropertyValue(n).trim()}
function setCssVar(n,v){document.documentElement.style.setProperty(n,v)}
