const STATE={authenticated:false,passwordSet:false,theme:{},commandHistory:[],historyIndex:-1,autoScroll:true,sseSource:null};
const IS_MOBILE='ontouchstart' in window;
let _appendCount=0,_rafPending=false;

class ParticleSystem{constructor(c){this.canvas=c;this.ctx=c.getContext('2d');this.particles=[];this.active=true;this.resize();this.init();window.addEventListener('resize',()=>this.resize())}resize(){this.canvas.width=window.innerWidth;this.canvas.height=window.innerHeight;if(!IS_MOBILE)this.initParticles()}init(){this.initParticles();this.animate()}initParticles(){const area=this.canvas.width*this.canvas.height;const n=IS_MOBILE?Math.floor(area/40000):Math.floor(area/8000);this.particles=[];for(let i=0;i<n;i++)this.particles.push({x:Math.random()*this.canvas.width,y:Math.random()*this.canvas.height,vx:(Math.random()-0.5)*(IS_MOBILE?0.2:0.5),vy:(Math.random()-0.5)*(IS_MOBILE?0.2:0.5),size:Math.random()*(IS_MOBILE?1:1.5)+(IS_MOBILE?0.3:0.5),opacity:Math.random()*(IS_MOBILE?0.2:0.3)+0.05,pulse:Math.random()*Math.PI*2})}setActive(a){this.active=a;if(a)this.animate()}animate(){if(!document.body.contains(this.canvas)||!this.active)return;this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height);const fc=getCssVar('--font-color')||'#00FF41';const r=parseInt(fc.slice(1,3),16),g=parseInt(fc.slice(3,5),16),b=parseInt(fc.slice(5,7),16);for(const p of this.particles){p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=this.canvas.width;if(p.x>this.canvas.width)p.x=0;if(p.y<0)p.y=this.canvas.height;if(p.y>this.canvas.height)p.y=0;p.pulse+=0.02;const a=p.opacity+Math.sin(p.pulse)*(IS_MOBILE?0.06:0.15);this.ctx.fillStyle=`rgba(${r},${g},${b},${a})`;this.ctx.beginPath();this.ctx.arc(p.x,p.y,p.size,0,Math.PI*2);this.ctx.fill()}if(!IS_MOBILE){for(let i=0;i<this.particles.length;i++){for(let j=i+1;j<this.particles.length;j++){const dx=this.particles[i].x-this.particles[j].x,dy=this.particles[i].y-this.particles[j].y,dist=Math.sqrt(dx*dx+dy*dy);if(dist<120){const a=(1-dist/120)*0.08;this.ctx.strokeStyle=`rgba(${r},${g},${b},${a})`;this.ctx.lineWidth=0.5;this.ctx.beginPath();this.ctx.moveTo(this.particles[i].x,this.particles[i].y);this.ctx.lineTo(this.particles[j].x,this.particles[j].y);this.ctx.stroke()}}}}requestAnimationFrame(()=>this.animate())}}
let _particleSys=null;

document.addEventListener('DOMContentLoaded',()=>{_particleSys=new ParticleSystem(document.getElementById('particleCanvas'));checkAuthStatus();document.addEventListener('keydown',handleKeyboard);const o=document.getElementById('consoleOutput');o.addEventListener('scroll',()=>{STATE.autoScroll=o.scrollHeight-o.scrollTop-o.clientHeight<50;document.getElementById('scrollHint').classList.toggle('visible',!STATE.autoScroll)},IS_MOBILE?{passive:true}:false);if(IS_MOBILE){o.style.webkitOverflowScrolling='touch';const sOverlay=document.getElementById('settingsOverlay');sOverlay.addEventListener('touchstart',function(e){if(e.target===sOverlay){this._ty=e.touches[0].clientY;this._closeGesture=false}},{passive:true});sOverlay.addEventListener('touchmove',function(e){if(!this._ty)return;const dy=e.touches[0].clientY-this._ty;if(dy>80&&sOverlay.querySelector('.settings-panel').scrollTop<=0){this._closeGesture=true;e.preventDefault()}if(this._closeGesture&&dy<0){this._ty=null;this._closeGesture=false}},{passive:false});sOverlay.addEventListener('touchend',function(e){if(this._closeGesture){toggleSettings()}this._ty=null;this._closeGesture=false},{passive:true})}});

async function checkAuthStatus(){try{const r=await fetch('/api/auth/status');const d=await r.json();STATE.passwordSet=d.passwordSet;if(d.authenticated){STATE.authenticated=true;showMainScreen();initMainScreen()}else showLoginScreen()}catch(e){showLoginScreen()}}
function showLoginScreen(){document.getElementById('loginScreen').classList.add('active');document.getElementById('mainScreen').classList.remove('active');if(_particleSys)_particleSys.setActive(true);const s=document.getElementById('setupForm'),l=document.getElementById('loginForm'),g=document.getElementById('loadingIndicator');g.style.display='none';if(STATE.passwordSet){s.style.display='none';l.style.display='block';var lp=document.getElementById('loginPassword');if(lp)lp.focus()}else{l.style.display='none';s.style.display='block';var sp=document.getElementById('setupPassword');if(sp)sp.focus()}}
function showMainScreen(){document.getElementById('loginScreen').classList.remove('active');document.getElementById('mainScreen').classList.add('active');if(_particleSys)_particleSys.setActive(false);document.getElementById('commandInput').focus()}

async function doSetup(){const p=document.getElementById('setupPassword').value,c=document.getElementById('setupConfirm').value,e=document.getElementById('setupError');if(p.length<6){e.textContent='密码至少需要6位';return}if(p!==c){e.textContent='两次输入的密码不一致';return}try{const r=await fetch('/api/auth/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:p})});const d=await r.json();if(d.success){e.textContent='';document.getElementById('loginPassword').value=p;doLogin()}else e.textContent=d.error||'设置失败'}catch(x){e.textContent='网络错误，请重试'}}
async function doLogin(){const p=document.getElementById('loginPassword').value,e=document.getElementById('loginError');if(!p){e.textContent='请输入密码';return}try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:p})});const d=await r.json();if(d.success){STATE.authenticated=true;showMainScreen();initMainScreen()}else{e.textContent=d.error||'密码错误';document.getElementById('loginPassword').value='';document.getElementById('loginPassword').focus()}}catch(x){e.textContent='网络错误，请检查服务器是否运行'}}
async function doLogout(){try{await fetch('/api/auth/logout',{method:'POST'})}catch(e){}STATE.authenticated=false;if(STATE.sseSource){STATE.sseSource.close();STATE.sseSource=null}showLoginScreen()}

function initMainScreen(){loadTheme();loadCommandHistory();connectSSE();document.getElementById('commandInput').focus()}
async function loadTheme(){try{const r=await fetch('/api/config/get');const d=await r.json();STATE.theme=d;applyThemeFromConfig(d);populateSettingsFromConfig(d)}catch(e){}}
function applyThemeFromConfig(c){if(c['theme.bg_color'])setCssVar('--bg-color',c['theme.bg_color']);if(c['theme.font_color'])setCssVar('--font-color',c['theme.font_color']);if(c['theme.border_color'])setCssVar('--border-color',c['theme.border_color']);if(c['theme.accent_color'])setCssVar('--accent-color',c['theme.accent_color']);if(c['theme.font_size'])setCssVar('--font-size',c['theme.font_size']+'px');if(c['theme.background_opacity'])setCssVar('--bg-opacity',c['theme.background_opacity'])}
function populateSettingsFromConfig(c){const e=id=>document.getElementById(id);const bg=c['theme.bg_color']||'#0C0C0C',fc=c['theme.font_color']||'#00FF41',bc=c['theme.border_color']||'#1A1A2E',ac=c['theme.accent_color']||'#E94560',sz=c['theme.font_size']||'14',op=c['theme.background_opacity']||'1.0';e('themeBgColor').value=bg;e('themeBgColorText').value=bg;e('themeFontColor').value=fc;e('themeFontColorText').value=fc;e('themeBorderColor').value=bc;e('themeBorderColorText').value=bc;e('themeAccentColor').value=ac;e('themeAccentColorText').value=ac;e('themeFontSize').value=sz;e('fontSizeValue').textContent=sz+'px';e('themeOpacity').value=op;e('opacityValue').textContent=op;e('settingsTimeout').value=c['session.timeout_minutes']||'30';e('settingsMaxLines').value=c['max_output_lines']||'5000';e('settingsPort').value=c['port']||'8080';e('settingsHttps').value=c['https.enabled']||'false';e('settingsCertFile').value=c['cert.file']||'';e('settingsWebRoot').value=c['web.root']||'';if(typeof htsToggle==='function')htsToggle()}
async function loadCommandHistory(){try{const r=await fetch('/api/command/history');const d=await r.json();STATE.commandHistory=d.history||[]}catch(e){}}

function connectSSE(){if(STATE.sseSource)STATE.sseSource.close();STATE.sseSource=new EventSource('/api/output/stream');STATE.sseSource.addEventListener('output',e=>{try{const d=JSON.parse(e.data);appendText(d.text,d.color||getCssVar('--font-color'))}catch(x){}});STATE.sseSource.addEventListener('clear',()=>{document.getElementById('consoleOutput').innerHTML=''});STATE.sseSource.onerror=()=>{const s=document.getElementById('connectionStatus');s.classList.add('disconnected');s.querySelector('.status-text').textContent='RECONNECTING...';setTimeout(()=>{if(STATE.sseSource&&STATE.sseSource.readyState===EventSource.OPEN){s.classList.remove('disconnected');s.querySelector('.status-text').textContent='CONNECTED'}},3000)};STATE.sseSource.onopen=()=>{const s=document.getElementById('connectionStatus');s.classList.remove('disconnected');s.querySelector('.status-text').textContent='CONNECTED'}}

function appendText(text,color){if(!text)return;const o=document.getElementById('consoleOutput');const s=document.createElement('span');s.className='output-line';s.style.color=color||getCssVar('--font-color');s.textContent=text;o.appendChild(s);const ml=parseInt(STATE.theme['max_output_lines']||5000);while(o.children.length>ml)o.removeChild(o.firstChild);_appendCount++;if(_appendCount>20){_appendCount=0;if(o.textContent.length>10000){const ks=o.children;let hf=Math.floor(ks.length/2);while(hf-->0&&o.firstChild)o.removeChild(o.firstChild)}}if(STATE.autoScroll&&!_rafPending){_rafPending=true;requestAnimationFrame(()=>{o.scrollTop=o.scrollHeight;_rafPending=false})}}

function sendCommand(){const i=document.getElementById('commandInput'),c=i.value.trim();if(!c)return;STATE.commandHistory.push(c);STATE.historyIndex=STATE.commandHistory.length;appendText('\n> '+c,getCssVar('--accent-color')||'#E94560');fetch('/api/command/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:c})}).then(r=>r.json()).then(d=>{if(!d.success)appendText('[ERROR] '+d.message,'#FF4444')}).catch(e=>{appendText('[ERROR] 请求失败: '+e.message,'#FF4444')});i.value='';i.focus();if(/^\/clear$/i.test(c))clearConsole()}
function clearConsole(){document.getElementById('consoleOutput').innerHTML='';fetch('/api/console/clear',{method:'POST'}).catch(()=>{})}

function handleKeyboard(e){if(!STATE.authenticated){if(e.key==='Enter'){if(document.getElementById('setupForm').style.display!=='none')doSetup();else doLogin()}return}const i=document.getElementById('commandInput'),so=document.getElementById('settingsOverlay').classList.contains('active');if(e.key==='Escape'&&so){toggleSettings();return}if(so)return;if(e.ctrlKey&&e.key==='l'){e.preventDefault();clearConsole();return}if(e.key==='Enter'&&document.activeElement===i){e.preventDefault();sendCommand();return}if(e.key==='ArrowUp'&&document.activeElement===i){e.preventDefault();if(STATE.commandHistory.length>0){STATE.historyIndex=Math.max(0,STATE.historyIndex-1);i.value=STATE.commandHistory[STATE.historyIndex]||''}return}if(e.key==='ArrowDown'&&document.activeElement===i){e.preventDefault();if(STATE.historyIndex<STATE.commandHistory.length-1){STATE.historyIndex++;i.value=STATE.commandHistory[STATE.historyIndex]||''}else{STATE.historyIndex=STATE.commandHistory.length;i.value=''}return}}

function toggleSettings(){const o=document.getElementById('settingsOverlay');o.classList.toggle('active');if(o.classList.contains('active')){fetch('/api/config/get').then(r=>r.json()).then(d=>{STATE.theme=d;populateSettingsFromConfig(d)}).catch(()=>{});loadSessions()}}
function applyThemeLive(){const bg=document.getElementById('themeBgColor').value,fc=document.getElementById('themeFontColor').value,bc=document.getElementById('themeBorderColor').value,ac=document.getElementById('themeAccentColor').value,sz=document.getElementById('themeFontSize').value,op=document.getElementById('themeOpacity').value;setCssVar('--bg-color',bg);setCssVar('--font-color',fc);setCssVar('--border-color',bc);setCssVar('--accent-color',ac);setCssVar('--font-size',sz+'px');setCssVar('--bg-opacity',op);document.getElementById('themeBgColorText').value=bg;document.getElementById('themeFontColorText').value=fc;document.getElementById('themeBorderColorText').value=bc;document.getElementById('themeAccentColorText').value=ac;document.getElementById('fontSizeValue').textContent=sz+'px';document.getElementById('opacityValue').textContent=op}
function syncColorFromText(id){const t=document.getElementById(id+'Text'),c=document.getElementById(id),v=t.value.trim();if(/^#[0-9A-Fa-f]{6}$/.test(v)){c.value=v;applyThemeLive()}}
async function saveTheme(){const p={'theme.bg_color':document.getElementById('themeBgColor').value,'theme.font_color':document.getElementById('themeFontColor').value,'theme.border_color':document.getElementById('themeBorderColor').value,'theme.accent_color':document.getElementById('themeAccentColor').value,'theme.font_size':document.getElementById('themeFontSize').value,'theme.background_opacity':document.getElementById('themeOpacity').value};try{const r=await fetch('/api/config/theme',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();showMsg('themeMsg',d.success?'主题已保存 ✓':'保存失败',d.success?'success':'error')}catch(e){showMsg('themeMsg','网络错误','error')}}
function resetTheme(){['themeBgColor','themeBgColorText'].forEach(i=>document.getElementById(i).value='#0C0C0C');['themeFontColor','themeFontColorText'].forEach(i=>document.getElementById(i).value='#00FF41');['themeBorderColor','themeBorderColorText'].forEach(i=>document.getElementById(i).value='#1A1A2E');['themeAccentColor','themeAccentColorText'].forEach(i=>document.getElementById(i).value='#E94560');document.getElementById('themeFontSize').value='14';document.getElementById('themeOpacity').value='1.0';document.getElementById('fontSizeValue').textContent='14px';document.getElementById('opacityValue').textContent='1.0';applyThemeLive();saveTheme()}
async function changePassword(){const o=document.getElementById('settingsOldPassword').value,n=document.getElementById('settingsNewPassword').value;if(!o||!n){showMsg('passwordMsg','请填写所有字段','error');return}if(n.length<6){showMsg('passwordMsg','新密码至少6位','error');return}try{const r=await fetch('/api/auth/changepassword',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({old_password:o,new_password:n})});const d=await r.json();if(d.success){showMsg('passwordMsg','密码已更新 ✓','success');document.getElementById('settingsOldPassword').value='';document.getElementById('settingsNewPassword').value=''}else showMsg('passwordMsg',d.error||'更新失败','error')}catch(e){showMsg('passwordMsg','网络错误','error')}}
async function saveServerConfig(){const t=document.getElementById('settingsTimeout').value,m=document.getElementById('settingsMaxLines').value;try{const r=await fetch('/api/config/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({'session.timeout_minutes':t,'max_output_lines':m})});const d=await r.json();showMsg('serverConfigMsg',d.success?'配置已保存 ✓':'保存失败',d.success?'success':'error')}catch(e){showMsg('serverConfigMsg','网络错误','error')}}
function htsToggle(){const e=document.getElementById('settingsHttps').value==='true';document.getElementById('ksRow').style.display=e?'':'none';document.getElementById('kpRow').style.display=e?'':'none'}
async function saveNetworkConfig(){const p={};const pt=document.getElementById('settingsPort').value;if(pt)p['port']=pt;const he=document.getElementById('settingsHttps').value;p['https.enabled']=he;const cf=document.getElementById('settingsCertFile').value.trim();if(cf)p['cert.file']=cf;const kf=document.getElementById('settingsKeyFile').value.trim();if(kf)p['key.file']=kf;const wr=document.getElementById('settingsWebRoot').value.trim();p['web.root']=wr;try{const r=await fetch('/api/config/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();const ok=d.success;showMsg('networkConfigMsg',ok?(d.restart?'已保存，服务重启中 ✓':'已保存 ✓'):'保存失败',ok?'success':'error')}catch(e){showMsg('networkConfigMsg','网络错误','error')}}
function showMsg(id,msg,type){const e=document.getElementById(id);e.textContent=msg;e.className='settings-msg '+type;setTimeout(()=>{e.textContent='';e.className='settings-msg'},3000)}
function getCssVar(n){return getComputedStyle(document.documentElement).getPropertyValue(n).trim()}
function setCssVar(n,v){document.documentElement.style.setProperty(n,v)}
async function loadSessions(){const el=document.getElementById('sessionsList');try{const r=await fetch('/api/sessions/list');const d=await r.json();if(!d.length){el.innerHTML='<span style="color:#555">无活跃会话</span>';return}let h='';for(const s of d){h+='<div style="padding:4px 0;cursor:pointer;border-bottom:1px solid #111" onclick="showSessionHistory(\''+s.id+'\')"><span style="color:#fff">'+escHtml(s.ip)+'</span><span style="font-size:10px;color:#444;margin-left:8px">'+new Date(s.loginTime).toLocaleString()+'</span></div>'}el.innerHTML=h}catch(e){el.innerHTML='<span style="color:var(--accent-color)">加载失败</span>'}}
async function showSessionHistory(sid){const el=document.getElementById('sessionHistory');try{const r=await fetch('/api/sessions/history?id='+encodeURIComponent(sid));const d=await r.json();if(!d.length){el.style.display='block';el.innerHTML='<span style="color:#555">该会话暂无命令记录</span>';return}let h='<div style="color:var(--accent-color);font-size:10px;margin-bottom:4px">命令历史 ('+d.length+'条)</div>';for(const e of d)h+='<div style="padding:1px 0"><span style="color:#888;font-size:10px">'+new Date(e.time).toLocaleString()+'</span> <span style="color:#ccc">'+e.cmd.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')+'</span></div>';el.style.display='block';el.innerHTML=h}catch(e){el.style.display='block';el.innerHTML='<span style="color:var(--accent-color)">加载失败</span>'}}
